"""
api/routers/tutor.py -- AI Tutor (Learning Buddy) endpoints.

POST  /api/v1/tutor/session                              Create a tutor session
POST  /api/v1/tutor/session/{session_id}/chat            Send a message, get tutor reply
POST  /api/v1/tutor/session/{session_id}/quiz            Generate a manual practice quiz
POST  /api/v1/tutor/session/{session_id}/complete-lesson Lesson checkpoint quiz (gated)
POST  /api/v1/tutor/session/{session_id}/next-lesson     Advance to next lesson / trigger module checkpoint
POST  /api/v1/tutor/session/{session_id}/answer          Submit a quiz answer
GET   /api/v1/tutor/session/{session_id}/history         Full conversation history
"""

import time

from fastapi import APIRouter, Depends, HTTPException

from api.config      import settings
from api.course_library import library
from api.dependencies import get_vector_store, get_embedder, get_retrieval_pipeline, get_progress_tracker, job_store
from api.schemas import (
    TutorSessionCreateRequest,  TutorSessionCreateResponse,
    TutorChatRequest,           TutorChatResponse,
    TutorQuizRequest,           TutorQuizResponse,
    TutorAnswerRequest,         TutorAnswerResponse,
    TutorHistoryResponse,
    CheckpointQuizResponse,
    LessonNavigationResponse,
    TutorQuizQuestion,
)
from modules.tutor.session_store import TutorSessionStore

router = APIRouter(prefix="/api/v1/tutor", tags=["AI Tutor"])

_session_store = TutorSessionStore()


def _get_engine(vector_store, embedder, retrieval_pipeline=None, progress_tracker=None):
    from modules.tutor.tutor_engine import TutorEngine
    if not settings.anthropic_api_key:
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY is not configured. Set it in the .env file.",
        )
    return TutorEngine(
        api_key=settings.anthropic_api_key,
        vector_store=vector_store,
        embedder=embedder,
        retrieval_pipeline=retrieval_pipeline,
        progress_tracker=progress_tracker,
    )


def _require_session(session_id: str):
    session = _session_store.get(session_id)
    if not session:
        raise HTTPException(status_code=404, detail=f"Session '{session_id}' not found.")
    return session


# -- Session navigation helpers ------------------------------------------------

def _get_lesson_data(session, module_idx: int, lesson_idx: int):
    if not session.course_script:
        return None
    for mod in session.course_script.get("modules", []):
        if mod["module_number"] == module_idx:
            for les in mod.get("lessons", []):
                if les["lesson_number"] == lesson_idx:
                    return les
    return None


def _get_module_data(session, module_idx: int):
    if not session.course_script:
        return None
    for mod in session.course_script.get("modules", []):
        if mod["module_number"] == module_idx:
            return mod
    return None


def _total_modules(session) -> int:
    if not session.course_script:
        return 0
    return len(session.course_script.get("modules", []))


def _lessons_in_module(session, module_idx: int) -> int:
    mod = _get_module_data(session, module_idx)
    return len(mod.get("lessons", [])) if mod else 0


# -- Endpoints -----------------------------------------------------------------

@router.post("/session", response_model=TutorSessionCreateResponse, status_code=201)
def create_session(
    request:          TutorSessionCreateRequest,
    progress_tracker = Depends(get_progress_tracker),
):
    """
    Create a new tutor session from a completed course script.

    Supply **one** of:
    - `job_id`   — from GET /api/v1/courses/jobs/{job_id} (generated by the course generation pipeline)
    - `script_id` — from GET /api/v1/courses/library (manually saved or library-stored scripts)

    Optionally pass a `learner_id` for progress tracking (email, UUID, etc. — defaults to "anonymous").
    """
    if not request.job_id and not request.script_id:
        raise HTTPException(status_code=422, detail="Provide either job_id or script_id.")

    script       = None
    source_file  = None

    # Try job store first (job_id), then library (script_id)
    if request.job_id:
        job = job_store.get_course(request.job_id)
        if job:
            if job.status != "completed":
                raise HTTPException(
                    status_code=400,
                    detail=f"Course job is '{job.status}' — wait for it to complete.",
                )
            script      = job.course_script
            source_file = job.source_file

    if script is None:
        lookup_id = request.script_id or request.job_id
        record    = library.get(lookup_id)
        if not record:
            raise HTTPException(
                status_code=404,
                detail=f"No completed course found for job_id/script_id '{lookup_id}'.",
            )
        script      = record["course_script"]
        source_file = record["source_file"]

    course_title    = script.get("course_title",    source_file)
    target_audience = script.get("target_audience", "learners")

    session = _session_store.create(
        source_file=source_file,
        course_title=course_title,
        target_audience=target_audience,
        current_module=request.current_module,
        current_lesson=request.current_lesson,
        course_script=script,
        learner_id=request.learner_id,
    )

    if progress_tracker:
        progress_tracker.record_lesson_start(
            request.learner_id, source_file,
            request.current_module, request.current_lesson,
        )

    lesson      = session.get_current_lesson_data()
    lesson_info = f" — starting at: {lesson['lesson_title']}" if lesson else ""

    return TutorSessionCreateResponse(
        session_id=session.session_id,
        course_title=course_title,
        current_module=session.current_module,
        current_lesson=session.current_lesson,
        has_course_script=True,
        learner_id=session.learner_id,
        message=f"Tutor session ready for '{course_title}'{lesson_info}. Start chatting!",
    )


@router.post("/session/{session_id}/chat", response_model=TutorChatResponse)
def chat(
    session_id:         str,
    request:            TutorChatRequest,
    vector_store=       Depends(get_vector_store),
    embedder=           Depends(get_embedder),
    retrieval_pipeline= Depends(get_retrieval_pipeline),
    progress_tracker=   Depends(get_progress_tracker),
):
    """
    Send a message to the AI Tutor and receive a reply.

    The tutor adapts its explanations based on the learner's tracked weak topics.
    """
    session = _require_session(session_id)
    engine  = _get_engine(vector_store, embedder, retrieval_pipeline, progress_tracker)
    try:
        reply = engine.chat(session, request.message, _session_store)
    except Exception as exc:
        err = str(exc)
        if "credit balance" in err.lower() or "402" in err or "400" in err:
            raise HTTPException(
                status_code=402,
                detail=(
                    "Anthropic API credits exhausted. Chat requires a live API connection. "
                    "You can still use /quiz, /complete-lesson, /answer, and /next-lesson without credits."
                ),
            )
        raise

    return TutorChatResponse(
        session_id=session_id,
        reply=reply,
        history_length=len(session.history),
    )


@router.post("/session/{session_id}/quiz", response_model=TutorQuizResponse)
def generate_quiz(
    session_id:   str,
    request:      TutorQuizRequest,
    vector_store= Depends(get_vector_store),
    embedder=     Depends(get_embedder),
):
    """
    Generate a manual practice quiz for the current lesson.

    This is ungraded practice — answers are not recorded towards progress.
    Use **complete-lesson** to trigger the gated checkpoint quiz instead.
    """
    session   = _require_session(session_id)
    engine    = _get_engine(vector_store, embedder)
    questions = engine.generate_quiz(session, request.num_questions, _session_store)

    lesson       = session.get_current_lesson_data()
    lesson_title = lesson["lesson_title"] if lesson else session.course_title

    return TutorQuizResponse(
        session_id=session_id,
        lesson_title=lesson_title,
        questions=questions,
    )


@router.post("/session/{session_id}/complete-lesson", response_model=CheckpointQuizResponse)
def complete_lesson(
    session_id:   str,
    vector_store= Depends(get_vector_store),
    embedder=     Depends(get_embedder),
    progress_tracker= Depends(get_progress_tracker),
):
    """
    Mark the current lesson as studied and receive a checkpoint quiz.

    The learner must answer all checkpoint questions (via **answer**) before
    calling **next-lesson**. Results are recorded for adaptive learning.
    """
    session = _require_session(session_id)

    if session.awaiting_checkpoint:
        raise HTTPException(
            status_code=400,
            detail="A checkpoint quiz is already active. Answer all pending questions first.",
        )
    if session.current_lesson_checkpointed:
        raise HTTPException(
            status_code=400,
            detail="This lesson is already checkpointed. Call next-lesson to proceed.",
        )

    engine    = _get_engine(vector_store, embedder, progress_tracker=progress_tracker)
    questions = engine.generate_checkpoint_quiz(
        session, num_questions=3, quiz_type="lesson_checkpoint", store=_session_store
    )

    lesson       = session.get_current_lesson_data()
    lesson_title = lesson["lesson_title"] if lesson else session.course_title

    return CheckpointQuizResponse(
        session_id=session_id,
        quiz_type="lesson_checkpoint",
        lesson_title=lesson_title,
        questions=[TutorQuizQuestion(**q) for q in questions],
        total_questions=len(questions),
        message=(
            f"Answer these {len(questions)} questions to complete '{lesson_title}'. "
            "Your results are tracked for personalised learning."
        ),
    )


@router.post("/session/{session_id}/next-lesson", response_model=LessonNavigationResponse)
def next_lesson(
    session_id:   str,
    vector_store= Depends(get_vector_store),
    embedder=     Depends(get_embedder),
    progress_tracker= Depends(get_progress_tracker),
):
    """
    Advance to the next lesson.

    - Requires the lesson checkpoint to be completed first (call **complete-lesson**).
    - If this is the last lesson in a module, returns a module checkpoint quiz instead
      of advancing. Answer all questions, then call **next-lesson** again to move forward.
    - Returns `action: "course_complete"` when the final lesson of the course is done.
    """
    session = _require_session(session_id)

    if session.awaiting_checkpoint:
        raise HTTPException(
            status_code=400,
            detail="A checkpoint quiz is active. Answer all pending questions before navigating.",
        )
    if not session.current_lesson_checkpointed:
        raise HTTPException(
            status_code=400,
            detail="Complete the lesson checkpoint first — call POST .../complete-lesson.",
        )

    is_last_lesson = session.current_lesson >= _lessons_in_module(session, session.current_module)
    is_last_module = session.current_module >= _total_modules(session)

    # Last lesson of a module and module checkpoint not yet done → trigger it
    if is_last_lesson and not session.module_checkpoint_done:
        engine    = _get_engine(vector_store, embedder, progress_tracker=progress_tracker)
        num_qs    = min(5, _lessons_in_module(session, session.current_module) * 2)
        questions = engine.generate_checkpoint_quiz(
            session, num_questions=max(3, num_qs),
            quiz_type="module_checkpoint", store=_session_store,
        )
        module = session.get_current_module_data()
        return LessonNavigationResponse(
            session_id=session_id,
            action="module_checkpoint",
            current_module=session.current_module,
            current_lesson=session.current_lesson,
            module_title=module["module_title"] if module else None,
            questions=[TutorQuizQuestion(**q) for q in questions],
            message=(
                f"You've completed all lessons in Module {session.current_module}! "
                f"Answer these {len(questions)} questions, then call next-lesson again to continue."
            ),
        )

    # Advance: last lesson + module checkpoint done → go to next module
    if is_last_lesson and session.module_checkpoint_done:
        if is_last_module:
            return LessonNavigationResponse(
                session_id=session_id,
                action="course_complete",
                current_module=session.current_module,
                current_lesson=session.current_lesson,
                message="Congratulations! You have completed the entire course.",
            )
        session.current_module        += 1
        session.current_lesson         = 1
        session.current_lesson_checkpointed = False
        session.module_checkpoint_done = False
    else:
        # Normal: advance to next lesson in same module
        session.current_lesson        += 1
        session.current_lesson_checkpointed = False

    session.lesson_started_at = time.time()
    session.updated_at        = time.time()
    _session_store.save()

    if progress_tracker and session.learner_id != "anonymous":
        progress_tracker.record_lesson_start(
            session.learner_id, session.source_file,
            session.current_module, session.current_lesson,
        )

    lesson  = session.get_current_lesson_data()
    module  = session.get_current_module_data()
    lt = lesson["lesson_title"] if lesson else f"Lesson {session.current_lesson}"
    mt = module["module_title"] if module else f"Module {session.current_module}"

    return LessonNavigationResponse(
        session_id=session_id,
        action="advanced",
        current_module=session.current_module,
        current_lesson=session.current_lesson,
        lesson_title=lt,
        module_title=mt,
        message=f"Now on Module {session.current_module}, Lesson {session.current_lesson}: {lt}",
    )


@router.post("/session/{session_id}/answer", response_model=TutorAnswerResponse)
def evaluate_answer(
    session_id:       str,
    request:          TutorAnswerRequest,
    progress_tracker= Depends(get_progress_tracker),
):
    """
    Submit a quiz answer for evaluation.

    Works for both manual practice quizzes and checkpoint quizzes.
    When the last checkpoint question is answered, `checkpoint_complete` is True
    and `checkpoint_score` is set in the response.
    """
    session = _require_session(session_id)

    try:
        q = session.get_quiz_question(request.question_id)
        if not q:
            raise HTTPException(
                status_code=404,
                detail="Question not found. It may have already been answered.",
            )

        correct = request.answer.strip().upper() == q.correct_answer.strip().upper()
        tutor_reply = (
            f"{'Correct!' if correct else f'Not quite — the correct answer is {q.correct_answer}.'} "
            f"{q.explanation}"
        )

        session.history.append({
            "role":    "user",
            "content": f"[Quiz] {q.question} — My answer: {request.answer.upper()}",
        })
        session.history.append({"role": "assistant", "content": tutor_reply})
        session.remove_quiz_question(request.question_id)

        # Track attempt in progress DB
        if progress_tracker and session.learner_id:
            progress_tracker.record_quiz_attempt(
                learner_id=session.learner_id,
                course_id=session.source_file,
                module_idx=session.current_module,
                lesson_idx=session.current_lesson,
                question_id=request.question_id,
                question_text=q.question,
                learner_answer=request.answer.upper(),
                correct_answer=q.correct_answer,
                is_correct=correct,
                topic_tag=q.topic_tag,
                quiz_type=q.quiz_type,
            )

        checkpoint_complete = False
        checkpoint_score    = None

        # Handle checkpoint state transitions
        if request.question_id in session.pending_checkpoint_qids:
            session.pending_checkpoint_qids.remove(request.question_id)
            session.checkpoint_answers.append(correct)

            if not session.pending_checkpoint_qids:
                # All checkpoint questions answered — compute score
                answers = session.checkpoint_answers
                score   = sum(answers) / len(answers) if answers else 0.0
                checkpoint_complete = True
                checkpoint_score    = round(score, 3)
                completed_type      = session.checkpoint_type

                session.awaiting_checkpoint = False
                session.checkpoint_answers  = []

                if completed_type == "lesson_checkpoint":
                    session.current_lesson_checkpointed = True
                    if progress_tracker and session.learner_id:
                        progress_tracker.record_lesson_checkpoint(
                            session.learner_id, session.source_file,
                            session.current_module, session.current_lesson, score,
                        )
                elif completed_type == "module_checkpoint":
                    session.module_checkpoint_done      = True
                    session.current_lesson_checkpointed = True   # unlocks next-lesson
                    if progress_tracker and session.learner_id:
                        progress_tracker.record_module_checkpoint(
                            session.learner_id, session.source_file,
                            session.current_module, score,
                        )

        session.updated_at = time.time()
        _session_store.save()

        return TutorAnswerResponse(
            session_id=session_id,
            question_id=request.question_id,
            correct=correct,
            correct_answer=q.correct_answer,
            explanation=q.explanation,
            checkpoint_complete=checkpoint_complete,
            checkpoint_score=checkpoint_score,
            checkpoint_type=session.checkpoint_type if checkpoint_complete else None,
        )

    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.get("/session/{session_id}/history", response_model=TutorHistoryResponse)
def get_history(session_id: str):
    """Retrieve the full conversation history for a session."""
    session = _require_session(session_id)
    return TutorHistoryResponse(
        session_id=session_id,
        course_title=session.course_title,
        current_module=session.current_module,
        current_lesson=session.current_lesson,
        history=session.history,
        total_messages=len(session.history),
    )
